export const emailData = [
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-15',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-16',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-14',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
  {
    Name: 'Campaign name',
    List: 'List 1',
    Subject: 'Email subject',
    State: '2024-09-13',
    Actions: '',
  },
];
