export const webhookslData = [
  {
    URL: 'user1@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-15',
    Actions: 'Edit',
  },
  {
    URL: 'user2@example.com',
    Events: 'Active',
    Date: 'No Complaints',
    lastUpdate: '2024-09-16',
    Actions: 'Edit',
  },
  {
    URL: 'user3@example.com',
    Events: 'Suppressed',
    Date: 'Complaint Received',
    lastUpdate: '2024-09-14',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
  {
    URL: 'user4@example.com',
    Events: 'Suppressed',
    Date: 'Invalid URL',
    lastUpdate: '2024-09-13',
    Actions: 'Edit',
  },
];
